### ISSUE TITLE
Missing reference

### ISSUE THREAD

**Issue by tromp** [john-light/validity-rollups#6]
The section on Grin mentions

> Work is ongoing to improve the privacy of Mimblewimble-based cryptocurrencies by combining the protocol with other privacy techniques. See for example Chaidos and Gelfer’s Lelantus-MW protocol.[163](https://bitcoinrollups.org/#fn:163)

This fails to mention MW Coinswap [1], the most important development in MW graph obfuscation, since, unlike Lelantus, it preserves MW's scalability (and simplicty) advantages.

[1] https://forum.grin.mw/t/mimblewimble-coinswap-proposal

**Comment by john-light** [comment]
Thanks @tromp . I did not intend for this section to be exhaustive of all efforts, and used Lelantus-MW as just one example I came across in my research to illustrate for the reader that such additional efforts to improve MW privacy do exist.
