### ISSUE TITLE
MW implementations

### ISSUE THREAD

**Issue by tromp** [john-light/validity-rollups#7]
> Grin is the second independent implementation of the Mimblewimble protocol

It was the first implementation. As shown at [1], implementation started in Oct 2016. It progressed through 4 testnets before launching mainnet in Jan 2019. While BEAM launched mainnet a few days earlier, their implementation only started in Mar 2018.

[1] https://docs.google.com/spreadsheets/d/1geg5HHgDO-ht0u6CSTHplJudr9kSGQYAoJvaKnfRhI4/edit#gid=137946732

**Comment by john-light** [comment]
@tromp  thank you for the information. By "second" I did mean the second to launch on mainnet, keeping consistent with the rest of the report which refers to the age of implementations by the launch date (i.e. when the implementation was considered "done" or at least "mainnet ready").
